name: 每日人才引进招聘监控

on:
  schedule:
    - cron: '0 23 * * *' # 每天北京时间 9:00 (UTC 1:00) 运行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 迁出代码
      uses: actions/checkout@v3

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 安装依赖库
      run: |
        pip install -r requirements.txt

    - name: 运行爬虫脚本
      env: 
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        python main.py

    - name: 提交并推送历史记录
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add history.txt
        git commit -m "Auto-save: Update history $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
